# Generated by Django 5.1.6 on 2025-02-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'About Images',
                'verbose_name_plural': 'About Images',
            },
        ),
        migrations.CreateModel(
            name='AboutPageBannerParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('feature1', models.CharField(max_length=255)),
                ('feature2', models.CharField(max_length=255)),
                ('feature3', models.CharField(max_length=255)),
                ('feature4', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AboutPageParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'About Page Paragraph',
                'verbose_name_plural': 'About Page Paragraph',
            },
        ),
        migrations.CreateModel(
            name='AboutPageVideoParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('videoUrl', models.URLField()),
            ],
            options={
                'verbose_name': 'About Page Video Paragraph',
            },
        ),
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('floor_plan', models.ImageField(upload_to='floor_plans/')),
                ('text', models.TextField()),
                ('rooms', models.PositiveIntegerField(blank=True, null=True)),
                ('area', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Apartment',
                'verbose_name_plural': 'Apartments',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_part1', models.CharField(max_length=255)),
                ('title_part2', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='banners/')),
                ('button_text', models.CharField(default='Request A Visit', max_length=50)),
                ('button_link', models.URLField(default='#')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LocationBenefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='icons/')),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Location Benefits',
                'verbose_name_plural': 'Location Benefits',
            },
        ),
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('logo_light', models.ImageField(upload_to='logos/')),
                ('logo_dark', models.ImageField(upload_to='logos/')),
            ],
            options={
                'verbose_name': 'Main Info',
                'verbose_name_plural': 'Main Info',
            },
        ),
        migrations.CreateModel(
            name='Prospecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='icons/')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Prospects',
                'verbose_name_plural': 'Prospects',
            },
        ),
    ]
