# Generated by Django 5.1.6 on 2025-02-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_maininfo_title_en_maininfo_title_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='apartments',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='apartments',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='apartments',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='apartments',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='apartments',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='apartments',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apartments',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apartments',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_text_en',
            field=models.CharField(default='Request A Visit', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_text_ru',
            field=models.CharField(default='Request A Visit', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_text_uz',
            field=models.CharField(default='Request A Visit', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_part1_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_part1_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_part1_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_part2_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_part2_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_part2_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
